services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'


# !Access PostgresSQL inside Container.
# * docker exec -it bookmgnmentsystem-postgres-1 psql -U myuser -d mydatabase
# ! Access PostgresSQL from Host Machine
# * psql -h localhost -p 5432 -U myuser -d mydatabase